name: ci

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
      - name: Switch branch
        run: git switch -c tmp
      - name: Git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Bump version
        id: bump_version
        run: |
          echo ::set-output name=VERSION::$(echo 1.1.1)
      - name: Push branch
        env:
          VERSION: ${{ steps.bump_version.outputs.VERSION }}
        run: |
          git branch -m ${VERSION}
          git push -u origin ${VERSION}
      - uses: actions/github-script@v4
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
          VERSION: ${{ steps.bump_version.outputs.VERSION }}
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore(*): bump v${process.env.VERSION}`,
              body: `Bump v${process.env.VERSION}`,
              head: `${context.repo.owner}:${process.env.VERSION}`,
              base: process.env.BRANCH
            })
