name: ci

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: actions/github-script@v4
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
          VERSION: ${{ steps.bump_version.outputs.VERSION }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore(*): bump v${process.env.VERSION}`,
              body: `Bump v${process.env.VERSION}`,
              head: `${context.repo.owner}:bump-v${process.env.VERSION}`,
              base: process.env.BRANCH
            })
