name: ci

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
      - name: Switch branch
        run: git switch -c tmp
      - name: Git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Push branch
        run: |
          git branch -m feature
          touch test.txt
          git add -A
          git commit -m "test commit"
          git push -u origin feature
      - name: Create pull request
        uses: actions/github-script@v4
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore`,
              body: `maybe created`,
              head: `${context.repo.owner}:feature`,
              base: process.env.BRANCH
            })
